In [1]:
!python -V

Python 3.7.9


In [2]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [5]:
a = "Hello"
b = "Python"
a + " " + b
print(a + " " + b)

Hello Python


In [6]:
# 사람이 생각하는 방식을 그래로 표현할 수 있는 언어
if 3 in [1,2,3,4]: print("3이 있습니다.")

3이 있습니다.


In [7]:
# 숫자(정수, 실수, 8진수, 16진수)
a = 123
b = -123
c = 0
d = 1.23
e = 0o177
f = 0xABC
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

123
-123
0
1.23
127
2748


In [8]:
# 사칙연산
a = 10
b = 2.3
c = a + b
d = a * b
e = a / b
f = a // b
g = a % b
h = 2 ** 2
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)

10
2.3
12.3
23.0
4.347826086956522
4.0
0.8000000000000007
4


In [10]:
String = '문자열'
Number = '273'
String + Number

'문자열273'

In [11]:
# 복합대입연산자
number = 100
number += 20
number += 30
number

150

In [ ]:
# -=, *=, /=
# Q. number = 100일 때, 20을 빼고 30을 더하는 연산을 복합연산자를 사용해서 구하세요

In [12]:
number = 100
number -= 20
number += 30
number

110

In [13]:
# 사용자 입력 : input()
input('인사말을 입력하세요>')

인사말을 입력하세요>안녕하세요


'안녕하세요'

In [15]:
# input 함수는 무엇을 입력해도 결과는 무조건 문자형
number = input('숫자를 입력하세요>')
print(number)
print(type(number))

숫자를 입력하세요>5
5
<class 'str'>


In [16]:
String_a = input('입력A> ')
String_b = input('입력B> ')
print(String_a+String_b)

입력A> 3
입력B> 3
33


In [ ]:
# Q. 문자열을 숫자 자료형으로 변환해서 숫자 연산을 수행하여 6을 출력하세요.

In [17]:
String_a = input('입력A> ')
String_b = input('입력B> ')
String_a = int(String_a)
String_b = int(String_b)
print(String_a+String_b)

입력A> 3
입력B> 3
6


In [ ]:
#Q. 3과 3.3을 입력하고 숫자 연산을 수행하여 6.3을 출력하세요

In [18]:
String_a = input("입력A> ")
String_b = input("입력B> ")
String_a = int(String_a)
String_b = float(String_b)
print(String_a+String_b)

입력A> 3
입력B> 3.3
6.3


In [ ]:
# Q. a = 52와 b = 52.273일때 a+b는 5252.273으로 출력되도록 a와 b를 
# 문자열 자료형으로 변환하세요.

In [21]:
a = str(52)
b = str(52.273) 
a + b 

'5252.273'

In [24]:
# 문자열: "", '', ''' '''
p1 = "python's value is great"
# p2 = 'python's value is great'
print(p1)
# print(p2)

python's value is great


In [26]:
s1 = '"python is valuable" he says.'
# s2 = ""python is valuable" he says."
print(s1)
# print(s2)

"python is valuable" he says.


In [27]:
p1 = 'python\'s value is great'
print(p1)

python's value is great


In [28]:
y1 = "Once you study data analysis\nYou need Python"
y2 = '''
Once you study data analysis
You need Python
'''
print(y1)
print(y2)

Once you study data analysis
You need Python

Once you study data analysis
You need Python



In [31]:
# 문자열 연산
a1 = 'Python'
a2 = ' is easy to learn'
print(a1+a2)
print(a1 * 3)
print('=' * 30)

Python is easy to learn
PythonPythonPython


In [35]:
# 들여쓰기
ld = ['a','b','c']
if 'a' in ld:
    print('a가 ld에 있습니다.')
else:
    print('ark ld에 없습니다.')

a가 ld에 있습니다.


In [36]:
# 포멧함수
f1 = '{}{}{}'.format(0,1,2)
print(f1)

012


In [38]:
f2 = '파이썬은 자바보다 {0}배 쉽습니다.'.format(3)
print(f2)

파이썬은 자바보다 3배 쉽습니다.


In [40]:
fd = 12345
f3 = '{:d}'.format(fd)
f4 = '{:10d}'.format(fd)
print(f3)
print(f4)

12345
     12345


In [44]:
ff = 12.3456789
f5 = '{:f}'.format(ff)
f6 = '{:15f}'.format(ff)
f7 = '{:.2f}'.format(ff)
f8 = '{:15.2f}'.format(ff)
print(f5)
print(f6)
print(f7)
print(f8)

12.345679
      12.345679
12.35
          12.35


In [45]:
f9 = '{} 선수가 {}등 입니다!!!'.format('홍길동',1)
print(f9)

홍길동 선수가 1등 입니다!!!


In [46]:
print('%s 선수가 %d등 입니다!!!' %('홍길동', 1))

홍길동 선수가 1등 입니다!!!


In [47]:
# 변수와 인자 전달
# 파이썬에서는 a와 b가 같은 객체인 [1,2,3]을 가리킨다.
a = [1,2,3]
b = a
a.append(4)
b

[1, 2, 3, 4]

In [48]:
# 함수에 객체를 인자로 넘기면 새로운 지역 변수가 생성되고 원래 객체를 복사하지 않고
# 참조만 함
def append_element(some_list, element):
    some_list.append(element)
    
data = [1,2,3]
append_element(data,4)
data

[1, 2, 3, 4]

In [50]:
# 자바와 같은 컴파일 언어와는 달리 파이썬에서는 객체 참조에 타입이 관여하지 않음
a = 5
print(type(a))
a = 'foo'
print(type(a))

<class 'int'>
<class 'str'>


In [52]:
'5' + '5'

'55'

In [53]:
# isinstance 함수 : 자료형 검사 
a = 5; b = 4.5
print(isinstance(a, int))

True


In [1]:
# 객체는 일반적으로 속성과 메서드 포함
a = 'foo'
a.capitalize()

'Foo'

In [56]:
# iterator 객체 - 반복 가능한 객체
# 대표적인 iterable 타입 : list, dict, set, str, bytes, tuple, range
# iterator 객체 - 값을 차례대로 꺼낼 수 있는 객체
# iterator는 iterable한 객체를 내장함수 또는 iterable 객체의 메서드로 객체를 생성
# 파이썬 내장함수 iter()를 사용해 iterator 객체를 생성
a = [1,2,3]
a_iter = iter(a)
print(type(a_iter))
for i in a:
    print(i,end=' ')

<class 'list_iterator'>
1 2 3 

In [ ]:
# dir() 내장 함수는 어떤 객체를 인자로 넣어주면 해당 객체가 어떤 변수와 메서드를
# 가지고 있는지 나열
b = {1,2,3}
dir(b)

In [3]:
def isiterable(obj):
    try:
        iter(obj)
        return True
    except TypeError:  # iterable 객체 아님
        return False

In [61]:
print(isiterable('a string'))
print(isiterable([1,2,3]))
print(isiterable(5))

True
True
False


In [62]:
# '==' 연산자 vs "is"
# 두 변수가 같은 객체를 가리키고 있는지 검사하려면 'is' 예약어 사용
# 두 변수의 값이 같은지 확인은 '=='을 사용
# list는 항상 새로운 파이썬 리스트를 생성하므로 c와 a는 구별됨
# is와 is not은 변수가 None인지 검사 시 사용
a = [1,2,3]
b = a
c = list(a)
print(c)
print(a is b)
print(a is c)
print(a == c)
print(a is None)

[1, 2, 3]
True
False
True
False


In [63]:
# 리스트, 사전, Numpy 배열, 사용자 정의 클래스 등 대부분의 객체는 변경 가능
a_list = ['foo', 2, [4,5]]
a_list[2] = (3,4)
print(a_list)

['foo', 2, (3, 4)]


In [ ]:
# 튜풀은 변경 불가
a_tuple = (3,4,(4,5))
a_tuple[1] = 'four'
print(a_tuple)

In [65]:
# 리스트로 변환 후 수정
a = list(a_tuple)
a[1] = 'four'
a

[3, 'four', (4, 5)]

In [ ]:
# 파이썬의 문자열은 변경 불가
a = 'this is a string'
a[10] = 'f'
a

In [67]:
# replace 함수 사용하여 수정
b = a.replace('string','longer string')
b

'this is a longer string'

In [68]:
# 불리언
True and True
True & False
False or False
False | True

True

In [70]:
# 형변환 함수 : str, bool, int, float
s = '3.14159'
fval = float(s)
bool(fval)
bool(0)

False

In [81]:
# 날짜와 시간
import datetime

now = datetime.datetime.now()
now
print(now.year,'년')
print(now.month,'월')
print(now.day,'일')
print(now.hour,'시')
print(now.minute,'분')
print(now.second,'초')


2020 년
12 월
28 일
14 시
11 분
34 초


In [75]:
from datetime import datetime, date, time
dt = datetime(2011,10,29,20,30,21)
print(dt.day)
print(dt.minute)
print(dt.date())
print(dt.time())

29
30
2011-10-29
20:30:21


In [76]:
# strftime 함수는 datetime을 문자열로 변환
dt.strftime('%m/%d/%Y %H:%M')

'10/29/2011 20:30'

In [77]:
# strptime 함수는 문자열을 datetime으로 변환
datetime.strptime('20091031','%Y%m%d')

datetime.datetime(2009, 10, 31, 0, 0)

In [78]:
dt1 = datetime(2011,10,29,20,30,21)
dt2 = datetime(2011,11,15,22,30,30)
delta = dt2 - dt1
print(delta,type(delta))

17 days, 2:00:09 <class 'datetime.timedelta'>


In [ ]:
# Q.format 함수를 이용해서 다음과 같은 형식으로 현재 날짜/시간을 출력하세요
# 2020년 7월 19일 10시 22분 36초

In [79]:
now = "{}년 {}월 {}일 {}시 {}분 {}초".format(now.year, now.month, now.day, now.hour, now.minute, \
                                       now.second)
print(now)

2020년 12월 28일 12시 36분 34초


In [ ]:
# Q 현재 시각으로 오전과 오후를 구분하는 프로그램을 작성하세요.

In [84]:
# A.
t = datetime.datetime.now()
if t.hour < 12:
    print('오전')
else:
    print('오후')

오후


In [85]:
# 제어문
# if, elif, else
x = 5
if x < 0:
    print("It's negative")
elif x == 0:
    print('Equal to zero')
elif 0 < x < 5:
    print('Positive but smaller than 5')
else:
    print('Psoitive and larger than or equal to 5')

Psoitive and larger than or equal to 5


Q. 커피 자판기 프로그램
- 시나리오 : 자판기 커피 재고 5잔, 커피 1잔 가격 300원, 재고 범위내에서 300원 이상 돈을 넣으면 거스름돈과 커피를 주고 그렇지 않으면 반환하며 재고가 소진되면 안내멘트 출력
- 각 Case별 멘트 출력은 상황에 맞게 창작
- while, if ~ elif ~ else 제어문을 사용하여 작성

In [86]:
coffee = 5

while(True):
    money = int(input("맛있는 커피를 300원에 드려요~~ 현금을 넣어주세요!!"))
    if money == 300:
        print("행복한 시간을 드리는 커피 드세요")
        coffee = coffee - 1
    elif money > 300:
        print("커피 맛있게 드시고 거스름돈 {}원 받는 것 잊지 마시구요".format(money-300))
        coffee = coffee - 1
    else:
        print("커피는 300원이예요~~ 현금을 다시 넣어주세요 ")
        print("남은 커피는 %d잔 입니다." % coffee)
    if coffee == 0:
        print("커피가 다 떨어졌네요~~ 잠시 판매중지합니다!!!")
        break   

맛있는 커피를 300원에 드려요~~ 현금을 넣어주세요!!300
행복한 시간을 드리는 커피 드세요
맛있는 커피를 300원에 드려요~~ 현금을 넣어주세요!!500
커피 맛있게 드시고 거스름돈 200원 받는 것 잊지 마시구요
맛있는 커피를 300원에 드려요~~ 현금을 넣어주세요!!300
행복한 시간을 드리는 커피 드세요
맛있는 커피를 300원에 드려요~~ 현금을 넣어주세요!!300
행복한 시간을 드리는 커피 드세요
맛있는 커피를 300원에 드려요~~ 현금을 넣어주세요!!300
행복한 시간을 드리는 커피 드세요
커피가 다 떨어졌네요~~ 잠시 판매중지합니다!!!


In [ ]:
# Q. "현금이 만원 이상 있으면 택시를 타고 그렇지 않으면 버스를 타세요" (if~else)

In [88]:
cash = 15000
# cash = 9000
if cash >= 10000:
    print('택시를 타고 가세요')
else:
    print('버스를 타고 가세요')

택시를 타고 가세요


In [89]:
a = 5; b = 7
c = 8; d = 4
a < b or c > d

True

In [90]:
#Q. "수입과 지출금액을 비교해서 수입이 많은면 저축 증가, 반대이면 부채 증가, 
# 같으면 현상 유지"
i = 5,000,000
e = 5,000,000

In [91]:
if i > e:
    print('저축이 늘고있네요!')
elif i < e:
    print('부채가 증가하고 있어요!!')
else:
    print('현상 유지하시는군요!!!')

현상 유지하시는군요!!!


In [95]:
# for 반복문
numbers = [5,15,6,20,7,25]
print(numbers)
for number in numbers:
    print(number,end=' ')

[5, 15, 6, 20, 7, 25]
5 15 6 20 7 25 

In [ ]:
"""
Q. A 학급에 총 10명의 학생이 있다. 이 학생들의 중간고사 점수는 다음과 같다.
[70, 60, 55, 75, 95, 90, 80, 80, 85, 100]
for문을 사용하여 A 학급의 평균 점수를 구해 보자.
"""

In [96]:
# A.
a = [70, 60, 55, 75, 95, 90, 80, 80, 85, 100]
sum = 0
for i in a:
    sum += i
    
average = sum/len(a)    
print(average)

79.0


In [ ]:
"""
리스트 중에서 홀수에만 2를 곱하여 저장하는 다음과 같은 코드가 있다.
numbers = [1, 2, 3, 4, 5]
result = []
for n in numbers:
    if n % 2 == 1:
        result.append(n*2)
위 코드를 리스트 내포(list comprehension)를 사용하여 표현해 보자.
"""

In [98]:
numbers = [1, 2, 3, 4, 5]
result = []
for n in numbers:
    if n % 2 == 1:
        result.append(n*2)
print(result)

[2, 6, 10]


In [99]:
# list comprehension
numbers = [1, 2, 3, 4, 5]
result = [n * 2 for n in numbers if n % 2 ==1]
result

[2, 6, 10]

In [100]:
# continue
sequence = [1,2,None,4,None,5]
total = 0
for value in sequence:
    if value is None:
        continue
    total += value
print(total)

12


In [102]:
# break
# 4 까지의 합
sequence = [1,2,3,4,5,6,7,8]
total_until_4 = 0
for value in sequence:
    if value == 5:
        break
    total_until_4 += value
print(total_until_4)

10


In [ ]:
# for ~ continue ~ break
# Q. 1 ~ 10 범위의 정수에서 1부터 5까지만 출력하세요"

In [103]:
for i in range(1,11):
    print(i, end=' ')
    if i < 5:
        continue
    else:
        break

1 2 3 4 5 

In [104]:
# break는 가장 안쪽에 있는 for문만 빠져나감
for i in range(4):
    for j in range(4):
        if j > i:
            break
        print((i,j))

(0, 0)
(1, 0)
(1, 1)
(2, 0)
(2, 1)
(2, 2)
(3, 0)
(3, 1)
(3, 2)
(3, 3)


In [106]:
# Q. numbers 리스트에서 15, 20, 25를 출력하세요.(for문과 if 조건 사용 필수)
numbers = [5, 15, 6, 20, 7, 25]
for number in numbers:
    if number < 10:
        continue
    else:
        print(number, end=' ')

15 20 25 

In [108]:
# while문
# while 문은 조건을 명시하여 해당 조건이 False가 되거나 break 문을 사용해서 
# 명시적으로 반복을 종료시까지 블록 내의 코드를 실행
x = 256
total = 0
while x > 0:
    if total > 500:
        break
    total += x
    x = x // 2
print(total)
print(x)

504
4


In [ ]:
# Q. 정수 1부터 n까지 더할 때 그 합이 1000보다 커지게 되는 n과 합을 구하세요.(while)

In [111]:
x = 1
sum = 0
while 1:
    sum = sum + x
    if sum > 1000:
        print(x)
        print(sum)
        break
    x = x + 1

45
1035


[과제] 아래와 같이 출력하는 코딩을 수행하세요.

In [5]:
i = 0
while True:
    i += 1
    if i > 5: break
    print('*'*i)        

*
**
***
****
*****


In [ ]:

*
**
***
****
*****

[과제] while continue break 문을 사용해 1부터 100까지의 정수중 5에서 95까지의 합을 구하세요.

In [4]:
sum = 0
x = 1
while x < 101:
    x = x + 1
    if x < 5:
        continue
    sum += x
    if x > 94:
        break
print(sum)
    

4550


[과제] while문을 사용해 1부터 1000까지의 정수 중 3의 배수의 합을 구해 보세요. 

In [6]:
sum = 0
i = 1
while i < 1001:
    if i % 3 == 0:
        sum += i
    i += 1
print(sum)

166833


In [113]:
# pass는 아무 것도 하지 않음을 나타냄
x = 0
if x < 0:
    print('negative')
elif x == 0:
    pass
else:
    print('positive')

In [118]:
# range 함수는 연속된 정수를 넘겨주는 이터레이터를 반환
# start, end, step 값을 지정
r1 = range(10)
print(list(r1))
r2 = range(0,20,2)
print(list(r2))
r3 = range(5, 0, -1)
list(r3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


[5, 4, 3, 2, 1]

In [119]:
# Q. 0 ~ 99,999 까지의 정수 중에서 3 또는 5의 배수 합계
sum = 0
for i in range(100000):
    if i % 3 == 0 or i % 5 == 0:
        sum += i
print(sum)

2333316668


In [120]:
# 삼항 표현식
x = 5
'Non-negative' if x >= 0 else 'Negative'

'Non-negative'

In [123]:
# 자료 구조
# 튜플 : 리스트와 비슷한 성질을 가지고 있는 자료형이지만 요소의 값을 변경할 수 없음
tuple1 = (1,2,3,4,5)
tuple2 = ('a','b','c')
tuple3 = (1,'a','abc',[1,2,3,4,5],['a','b','c'])
# tuple1[0] = 6

def myfunc():
    print('안녕하세요')

tuple4 = (1,2,myfunc)
print(tuple4[:2])
tuple4[2]()


(1, 2)
안녕하세요


In [9]:
# 각 슬롯에 저장된 객체를 변경하는 것은 불가능
tup = tuple(['foo',[1,2],True])
tup[2] = False

TypeError: 'tuple' object does not support item assignment

In [8]:
# 튜플에 추가하는 것은 가능
tup[1].append(3)
tup

('foo', [1, 2, 3], True)

In [10]:
# 순차 자료형으로 값을 분리
tup = 4,5,(6,7)
a,b,(c,d) = tup
d

7

In [11]:
# 튜플이나 리스트를 순회시 값을 분리하는 기능
seq = [(1,2,3),(4,5,6),(7,8,9)]
for a, b, c in seq:
    print('a={0}, b={1}, c={2}'.format(a,b,c))

a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


In [12]:
# count
a = (1,2,3,3,4,4,5,5,5)
a.count(5)

3

파이썬에서 함수와 메서드의 차이
- 프로그래밍 언어에 있어서 함수(function)라는 것은 어떠한 기능을 수행
- 메서드도 함수처럼 어떠한 기능을 수행
- 메서드는 클래스 및 객체(object)와 연관되어 있는 함수
- 함수가 메서드보다 더 큰 개념. 그래서 메서드를 부를 때 포괄적으로 함수로 지칭
- 함수는 sum(), abs() 같이 독립적으로 사용되는 반면, 메서드는 a라는 객체가 존재할 때 a.upper(), a.lower()와 같은 형태로 사용

In [14]:
# 리스트 : []로 표시하며 []안의 요소를 콤마로 구분하여 순서있게 나열
list1 = [1,2,3,4,5]
list2 = ['a','b','c']
list3 = [1,'a','abc',[1,2,3,4,5],['a','b','c']]
list1[0] = 6
print(list1)
def myfunc():
    print('안녕하세요')
list4 = [1,2,myfunc]
list4[2]() 


[6, 2, 3, 4, 5]
안녕하세요


In [17]:
# 리스트 함수는 이터레이터나 제너레이터 표현에서 실제 값을 모두 담기 위한 용도로 사용
gen = range(10)
print(list(gen))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [18]:
# insert 메서드 사용, 특정 위치에 값 추가
b_list = ['foo','bar','baz']
b_list.insert(1,'red')
b_list

['foo', 'red', 'bar', 'baz']

In [21]:
# pop 메서드는 특정 위치의 값을 반환하고 해당 값을 리스트에서 삭제
print(b_list)
print(b_list.pop(2))
print(b_list)

['foo', 'red', 'baz']
baz
['foo', 'red']


In [22]:
# remove 메서드 : 삭제
b_list = ['foo', 'red', 'bar', 'baz']
b_list.remove('foo')
b_list

['red', 'bar', 'baz']

In [23]:
# in 예약어를 사용, 리스트에 어떤 값이 있는지 검사
'dwarf' in b_list

False

In [24]:
# not in
'dwarf' not in b_list

True

In [25]:
# extend 메서드
x = [4, None, 'foo']
x.extend([7,8,(2,3)])
x

[4, None, 'foo', 7, 8, (2, 3)]

In [37]:
# 정렬 : 새로운 리스트를 생성하지 않고 있는 그대로 리스트를 정렬
a = [7,2,5,1,3]
a.sort()
print(a,type(a))

[1, 2, 3, 5, 7] <class 'list'>


In [27]:
# 문자열의 길이 순으로 정렬
b = ['saw','small','He','foxes','six']
b.sort(key = len)
b

['He', 'saw', 'six', 'small', 'foxes']

In [28]:
# sorted 함수 : 정렬된 복사본을 생성
sorted([5,2,3,1,5])

[1, 2, 3, 5, 5]

In [46]:
# Numpy np.sort()는 원본 행렬을 변경하지 않고 정렬된 형태로 변환
import numpy as np
a1 = [7,2,5,1,3]
ar1 = np.array(a1)
print(np.sort(ar1))
print(np.sort(ar1)[::-1]) # 내림차순
print(ar1,type(ar1))

[1 2 3 5 7]
[7 5 3 2 1]
[7 2 5 1 3] <class 'numpy.ndarray'>


In [36]:
# ndarray.sort()는 원본 행렬 자체을 변환
import numpy as np
a2 = [7,2,5,1,3]
ar2 = np.array(a2)
print(ar2.sort())
print(ar2)

None
[1 2 3 5 7]


In [42]:
# 정렬된 리스트를 유지한 상태에서 인자를 포함시킬 위치를 반환
import bisect
c = [1,2,2,2,3,4,7]
print(bisect.bisect(c,2))
print(bisect.bisect(c, 5))
bisect.insort(c,6)
c

4
6


[1, 2, 2, 2, 3, 4, 6, 7]

In [43]:
# 슬라이싱
seq = [7,2,3,7,5,6,0,1]
print(seq[3:4])
seq[-6:-2]

[7]


[3, 7, 5, 6]

In [44]:
# 두번째 콜론 다음에 간격(step)을 지정
seq[::2]

[7, 3, 5, 0]

In [45]:
# 간격 값으로 -1을 사용하면 리스트나 튜플을 역순으로 반환
print(seq)
seq[::-1]

[7, 2, 3, 7, 5, 6, 0, 1]


[1, 0, 6, 5, 7, 3, 2, 7]

In [47]:
# enumerate 함수
some_list = ['foo','bar','baz']
mapping = {}
for i, v in enumerate(some_list):
    mapping[v] = i
mapping

{'foo': 0, 'bar': 1, 'baz': 2}

In [48]:
# zip 함수 : 서로 짝지어서 튜플의 리스트를 생성
seq1 = ['foo','bar','baz']
seq2 = ['one','two','three']
zipped = zip(seq1,seq2)
list(zipped)

[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]

In [49]:
# 리스트의 크기는 넘겨받은 순차자료중 가장 짧은 크기로 정해짐
seq3 = [False, True]
list(zip(seq1,seq2,seq3))

[('foo', 'one', False), ('bar', 'two', True)]

In [50]:
# 여러 개의 순차 자료형을 동시에 순회
for i, (a,b) in enumerate(zip(seq1,seq2)):
    print('{0}: {1}, {2}'.format(i,a,b))

0: foo, one
1: bar, two
2: baz, three


In [51]:
pichers = [('Nolan','Ryan'),('Roger','Clemens'),('Schilling','Curt')]
first_names, last_names = zip(*pichers)
print(first_names)
print(last_names)

('Nolan', 'Roger', 'Schilling')
('Ryan', 'Clemens', 'Curt')


In [52]:
# reversed 함수 : 순차 자료형을 역순으로 순회
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [55]:
# 사전 : 키와 값을 하나의 요소로 하는 순서가 없는 집합
# 시퀀스 자료형이 아니며 인덱싱으로 값을 접근할 수 없음
dict1 = {'a':1,'b':2,'c':3}
print(dict1['a'])
dict1['b'] = 7
print(dict1)
print(len(dict1))

1
{'a': 1, 'b': 7, 'c': 3}
3


In [57]:
# 사전에 키가 있는지 확인
'b' in dict1

True

In [59]:
d1 = {'a':'some value','b':[1,2,3,4]}
d1[7] = 'an integer'
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [61]:
list(d1.keys())
list(d1.values())

['some value', [1, 2, 3, 4], 'an integer']

In [62]:
# 하나의 사전을 다른 사전과 합칠 수 있음
d1.update({'b':'foo','c':12})
d1

{'a': 'some value', 'b': 'foo', 7: 'an integer', 'c': 12}

In [64]:
# 2개짜리 튜플의 리스트를 인자로 받아서 사전을 생성
print(list(zip(range(5),reversed(range(5)))))
mapping = dict(zip(range(5),reversed(range(5))))
mapping

[(0, 4), (1, 3), (2, 2), (3, 1), (4, 0)]


{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

In [65]:
# 집합 : 중복을 허용하지 않으며 순서가 없다.
set([2,2,2,1,3,3])

{1, 2, 3}

In [71]:
# 집합은 리스트나 튜플로 변환 후 인덱싱
s1 = set([1,2,3,4,5])
print(s1)
s2 = set('Hello')
print(s2)
l1 = list(s1)
print(l1)
print(l1[1])
l2 = list(s2)
print(l2)
print(l2[1])

{1, 2, 3, 4, 5}
{'e', 'o', 'l', 'H'}
[1, 2, 3, 4, 5]
2
['e', 'o', 'l', 'H']
o


In [72]:
# 합집합, 교집합
a = {1,2,3,4,5}
b = {3,4,5,6,7,8}
print(a.union(b))
print(a|b)
print(a.intersection(b))
print(a&b)

{1, 2, 3, 4, 5, 6, 7, 8}
{1, 2, 3, 4, 5, 6, 7, 8}
{3, 4, 5}
{3, 4, 5}


In [75]:
c = a.copy()
c |= b
print(c)
d = a.copy()
d &= b
print(d)

{1, 2, 3, 4, 5, 6, 7, 8}
{3, 4, 5}


In [76]:
# 부분집합 확인
a_set = {1,2,3,4,5}
{1,2,3}.issubset(a_set)

True

In [77]:
# 확대집합 확인
a_set.issuperset({1,2,3})

True

Q. 태어난 연도를 입력받아 띠를 출력하는 프로그램을 작성하세요.

원숭이, 닭, 개, 돼지, 쥐, 소, 범, 토끼, 용, 뱀, 말, 양띠

In [78]:
birth_year = input("태어난 연도를 입력하세요> ")
byear = int(birth_year)
if byear % 12 == 0:
    print("원숭이띠입니다.")
elif byear % 12 == 1:
    print("닭띠입니다.")
elif byear % 12 == 2:
    print("개띠입니다.")
elif byear % 12 == 3:
    print("돼지띠입니다.")
elif byear % 12 == 4:
    print("쥐띠입니다.")
elif byear % 12 == 5:
    print("소띠입니다.")
elif byear % 12 == 6:
    print("범띠입니다.")
elif byear % 12 == 7:
    print("토끼띠입니다.")
elif byear % 12 == 8:
    print("용띠입니다.")
elif byear % 12 == 9:
    print("뱀띠입니다.")
elif byear % 12 == 10:
    print("말띠입니다.")
else:
    print("양띠입니다.")

태어난 연도를 입력하세요> 1995
돼지띠입니다.


In [80]:
# 효율화
animal = ['원숭이', '닭', '개', '돼지', '쥐', '소', '범', '토끼', '용', '뱀', '말', '양띠']
year = int(input("태어난 연도를 입력하세요> "))
print('{}띠입니다.'.format(animal[year%12]))

태어난 연도를 입력하세요> 1995
돼지띠입니다.


Q. 계절 구분 프로그램

- 시나리오 : 3 ~ 5월은 봄, 6 ~ 8월은 여름, 9 ~ 11월은 가을, 12 ~ 2월은 겨울로 구분. 지금 계절을 알려주는 프로그램
- 각 계절별 출력 멘트는 계절에 맞게 창작
- if 조건문으로 datetime 모듈을 import해서 datetime.now 함수를 사용해서 작성 

In [81]:
import datetime
t = datetime.datetime.now()
if 3<= t.month <=5:
    print('봄')
if 6<= t.month <=8:
    print('여름')
if 9<= t.month <=11:
    print('가을')
if 1 <= t.month <=2 or t.month==12:
    print('겨울')

겨울
